module Widgets.Models.ModelChoiceField exposing (..)

{-| Do not manually edit this file, it was auto-generated by djelm
<https://github.com/Confidenceman02/django-elm>
-}

import Json.Decode as Decode
import Json.Decode.Pipeline exposing (required, optional, hardcoded)


type alias ToModel =
    { help_text : String
    , auto_id : String
    , id_for_label : String
    , label : Maybe String
    , name : String
    , widget_type : String
    , options : List Options_
    }

type Options_
    = Course Options_Course__


type alias Options_Course__ =
    { choice_label : String
    , value : String
    , selected : Bool
    , instance : Options_Course__Instance__
    }

type alias Options_Course__Instance__ =
    { id : Int
    , name : String
    , instructor : String
    , duration : Int
    , rating : Float
    }


toModel : Decode.Decoder ToModel
toModel =
    Decode.succeed ToModel
        |> required "help_text" Decode.string
        |> required "auto_id" Decode.string
        |> required "id_for_label" Decode.string
        |> required "label" (Decode.nullable Decode.string)
        |> required "name" Decode.string
        |> required "widget_type" Decode.string
        |> required "options" (Decode.list (Decode.oneOf [Decode.map Course options_Course__Decoder]))

options_Course__Decoder : Decode.Decoder Options_Course__
options_Course__Decoder =
    Decode.succeed Options_Course__
        |> required "choice_label" Decode.string
        |> required "value" Decode.string
        |> required "selected" Decode.bool
        |> required "instance" options_course__instance__Decoder

options_course__instance__Decoder : Decode.Decoder Options_Course__Instance__
options_course__instance__Decoder =
    Decode.succeed Options_Course__Instance__
        |> required "id" Decode.int
        |> required "name" Decode.string
        |> required "instructor" Decode.string
        |> required "duration" Decode.int
        |> required "rating" Decode.float
